apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-prometheus
  namespace: myprod
spec:
  releaseName: azure-arc-prometheus-myprod
  chart:
    git: https://github.com/prometheus-community/helm-charts
    path: charts/prometheus      
    ref: main
